//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.Erpsuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_CM_PROCESSARANALISEFATURAMEN
    /// </summary>
    public partial interface ICmProcessaranalisefaturamento : IEntityBase
    {
        
        /// <summary>
        /// Data final (DATAFINAL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Datafinal
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data inicial (DATAINICIAL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Datainicial
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        CmProcessaranalisefaturamentoStatusListaItens Status
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_CM_PROCESSARANALISEFATURAMEN
    /// </summary>
    public partial interface ICmProcessaranalisefaturamentoDao : IBusinessEntityDao<ICmProcessaranalisefaturamento>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_CM_PROCESSARANALISEFATURAMEN
    /// </summary>
    public partial class CmProcessaranalisefaturamentoDao : BusinessEntityDao<CmProcessaranalisefaturamento, ICmProcessaranalisefaturamento>, ICmProcessaranalisefaturamentoDao
    {
        
        public static CmProcessaranalisefaturamentoDao CreateInstance()
        {
            return CreateInstance<CmProcessaranalisefaturamentoDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo STATUS.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
    public class CmProcessaranalisefaturamentoStatusListaItens : ListItems<CmProcessaranalisefaturamentoStatusListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Aguadando Processamento .
        /// </summary>
        public static CmProcessaranalisefaturamentoStatusListaItens ItemAguadandoProcessamento;
        
        /// <summary>
        /// Valor = 2, Item = Processando.
        /// </summary>
        public static CmProcessaranalisefaturamentoStatusListaItens ItemProcessando;
        
        /// <summary>
        /// Valor = 3, Item = Processado.
        /// </summary>
        public static CmProcessaranalisefaturamentoStatusListaItens ItemProcessado;
        
		public static implicit operator CmProcessaranalisefaturamentoStatusListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(CmProcessaranalisefaturamentoStatusListaItens item)
		{
			return item.Index;
		}
        
        static CmProcessaranalisefaturamentoStatusListaItens()
        {
			ItemAguadandoProcessamento = new CmProcessaranalisefaturamentoStatusListaItens {Index = 1, Description ="Aguadando Processamento "};
			ItemProcessando = new CmProcessaranalisefaturamentoStatusListaItens {Index = 2, Description ="Processando"};
			ItemProcessado = new CmProcessaranalisefaturamentoStatusListaItens {Index = 3, Description ="Processado"};

			Items.Add(ItemAguadandoProcessamento);
			Items.Add(ItemProcessando);
			Items.Add(ItemProcessado);

        }
    }
    
    /// <summary>
    /// CmProcessaranalisefaturamento
    /// </summary>
    [EntityDefinitionName("K_CM_PROCESSARANALISEFATURAMEN")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class CmProcessaranalisefaturamento : BusinessEntity<CmProcessaranalisefaturamento>, ICmProcessaranalisefaturamento
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Datafinal = "DATAFINAL";
			public const string Datainicial = "DATAINICIAL";
			public const string Nome = "NOME";
			public const string Status = "STATUS";
		}

        
        /// <summary>
        /// Data final (DATAFINAL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Datafinal
        {
            get
            {
                return Fields["DATAFINAL"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAFINAL"] = value;
            }
        }
        
        /// <summary>
        /// Data inicial (DATAINICIAL.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Datainicial
        {
            get
            {
                return Fields["DATAINICIAL"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINICIAL"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public CmProcessaranalisefaturamentoStatusListaItens Status
        {
            get
            {
                ListItem listItem = Fields["STATUS"] as ListItem;
				if (listItem != null)
					return new CmProcessaranalisefaturamentoStatusListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["STATUS"] = new ListItem(value.Index, value.Description);
				else
					Fields["STATUS"] = null;
            }
        }
    }
}
