//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.ErpSuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_CM_PROGRAMADOS
    /// </summary>
    public partial interface ICmProgramados : IEntityBase
    {
        
        /// <summary>
        /// Data alteração (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> DataAlteracao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Datafim
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data inclusão (DATAINCLUSAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> DataInclusao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Datainicio (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Datainicio
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioAlterouInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle UsuarioAlterouHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioIncluiuInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle UsuarioIncluiuHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_CM_PROGRAMADOS
    /// </summary>
    public partial interface ICmProgramadosDao : IBusinessEntityDao<ICmProgramados>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_CM_PROGRAMADOS
    /// </summary>
    public partial class CmProgramadosDao : BusinessEntityDao<CmProgramados, ICmProgramados>, ICmProgramadosDao
    {
        
        public static CmProgramadosDao CreateInstance()
        {
            return CreateInstance<CmProgramadosDao>();
        }
    }
    
    /// <summary>
    /// CmProgramados
    /// </summary>
    [EntityDefinitionName("K_CM_PROGRAMADOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class CmProgramados : BusinessEntity<CmProgramados>, ICmProgramados
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string DataAlteracao = "DATAALTERACAO";
			public const string Datafim = "DATAFIM";
			public const string DataInclusao = "DATAINCLUSAO";
			public const string Datainicio = "DATAINICIO";
			public const string Nome = "NOME";
			public const string UsuarioAlterou = "USUARIOALTEROU";
			public const string UsuarioIncluiu = "USUARIOINCLUIU";
		}

        
        /// <summary>
        /// Data alteração (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return Fields["DATAALTERACAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAALTERACAO"] = value;
            }
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Datafim
        {
            get
            {
                return Fields["DATAFIM"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAFIM"] = value;
            }
        }
        
        /// <summary>
        /// Data inclusão (DATAINCLUSAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return Fields["DATAINCLUSAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINCLUSAO"] = value;
            }
        }
        
        /// <summary>
        /// Datainicio (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Datainicio
        {
            get
            {
                return Fields["DATAINICIO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINICIO"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioAlterouInstance
        {
            get
            {
                if (UsuarioAlterou.Handle == null)
                {
					return null;
                }
                return UsuarioAlterou.Instance;
            }
            set
            {
                if (value == null)
                {
					UsuarioAlterou = null;
					return;
                }
                UsuarioAlterou.Instance = (Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle UsuarioAlterouHandle
        {
            get
            {
                return UsuarioAlterou.Handle;
            }
            set
            {
                UsuarioAlterou.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuário alterou (USUARIOALTEROU.)
        /// Opcional = S, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios> UsuarioAlterou
        {
            get
            {
                return (Fields["USUARIOALTEROU"] as EntityAssociation).Wrap<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios>(Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.UsuarioAlterou.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.UsuarioAlterou.Instance = value.Instance;
                    }
                    else
                    {
                        this.UsuarioAlterou.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioIncluiuInstance
        {
            get
            {
                if (UsuarioIncluiu.Handle == null)
                {
					return null;
                }
                return UsuarioIncluiu.Instance;
            }
            set
            {
                if (value == null)
                {
					UsuarioIncluiu = null;
					return;
                }
                UsuarioIncluiu.Instance = (Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle UsuarioIncluiuHandle
        {
            get
            {
                return UsuarioIncluiu.Handle;
            }
            set
            {
                UsuarioIncluiu.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuário incluiu (USUARIOINCLUIU.)
        /// Opcional = S, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios> UsuarioIncluiu
        {
            get
            {
                return (Fields["USUARIOINCLUIU"] as EntityAssociation).Wrap<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios>(Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.UsuarioIncluiu.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.UsuarioIncluiu.Instance = value.Instance;
                    }
                    else
                    {
                        this.UsuarioIncluiu.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
