//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.Erpsuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_CM_PROGRAMADOPRODUTOS
    /// </summary>
    public partial interface ICmProgramadoprodutos : IEntityBase
    {
        
        /// <summary>
        /// Data alteração (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> DataAlteracao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data inclusão (DATAINCLUSAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> DataInclusao
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Corporativo.Definicoes.Materiais.IPDProduto ProdutoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle ProdutoHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Esp.ErpSuporte.Caisp.Business.Entidades.ICmProgramados ProgramadosInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle ProgramadosHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 99999999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<long> Quantidade
        {
            get;
            set;
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        CmProgramadoprodutosStatusListaItens Status
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioAlterouInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle UsuarioAlterouHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioincluiuInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Handle UsuarioincluiuHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_CM_PROGRAMADOPRODUTOS
    /// </summary>
    public partial interface ICmProgramadoprodutosDao : IBusinessEntityDao<ICmProgramadoprodutos>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_CM_PROGRAMADOPRODUTOS
    /// </summary>
    public partial class CmProgramadoprodutosDao : BusinessEntityDao<CmProgramadoprodutos, ICmProgramadoprodutos>, ICmProgramadoprodutosDao
    {
        
        public static CmProgramadoprodutosDao CreateInstance()
        {
            return CreateInstance<CmProgramadoprodutosDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo STATUS.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
    public class CmProgramadoprodutosStatusListaItens : ListItems<CmProgramadoprodutosStatusListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Aguardando Carregamento.
        /// </summary>
        public static CmProgramadoprodutosStatusListaItens ItemAguardandoCarregamento;
        
        /// <summary>
        /// Valor = 2, Item = Item Carregado.
        /// </summary>
        public static CmProgramadoprodutosStatusListaItens ItemItemCarregado;
        
		public static implicit operator CmProgramadoprodutosStatusListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(CmProgramadoprodutosStatusListaItens item)
		{
			return item.Index;
		}
        
        static CmProgramadoprodutosStatusListaItens()
        {
			ItemAguardandoCarregamento = new CmProgramadoprodutosStatusListaItens {Index = 1, Description ="Aguardando Carregamento"};
			ItemItemCarregado = new CmProgramadoprodutosStatusListaItens {Index = 2, Description ="Item Carregado"};

			Items.Add(ItemAguardandoCarregamento);
			Items.Add(ItemItemCarregado);

        }
    }
    
    /// <summary>
    /// CmProgramadoprodutos
    /// </summary>
    [EntityDefinitionName("K_CM_PROGRAMADOPRODUTOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class CmProgramadoprodutos : BusinessEntity<CmProgramadoprodutos>, ICmProgramadoprodutos
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string DataAlteracao = "DATAALTERACAO";
			public const string DataInclusao = "DATAINCLUSAO";
			public const string Produto = "PRODUTO";
			public const string Programados = "PROGRAMADOS";
			public const string Quantidade = "QUANTIDADE";
			public const string Status = "STATUS";
			public const string UsuarioAlterou = "USUARIOALTEROU";
			public const string Usuarioincluiu = "USUARIOINCLUIU";
		}

        
        /// <summary>
        /// Data alteração (DATAALTERACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> DataAlteracao
        {
            get
            {
                return Fields["DATAALTERACAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAALTERACAO"] = value;
            }
        }
        
        /// <summary>
        /// Data inclusão (DATAINCLUSAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto, Segundo
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> DataInclusao
        {
            get
            {
                return Fields["DATAINCLUSAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINCLUSAO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Corporativo.Definicoes.Materiais.IPDProduto ProdutoInstance
        {
            get
            {
                if (Produto.Handle == null)
                {
					return null;
                }
                return Produto.Instance;
            }
            set
            {
                if (value == null)
                {
					Produto = null;
					return;
                }
                Produto.Instance = (Benner.Corporativo.Definicoes.Materiais.PDProduto) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle ProdutoHandle
        {
            get
            {
                return Produto.Handle;
            }
            set
            {
                Produto.Handle = value;
            }
        }
        
        /// <summary>
        /// Produto (PRODUTO.)
        /// Opcional = N, Invisível = False, Pesquisar = PD_PRODUTOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Corporativo.Definicoes.Materiais.PDProduto> Produto
        {
            get
            {
                return (Fields["PRODUTO"] as EntityAssociation).Wrap<Benner.Corporativo.Definicoes.Materiais.PDProduto>(Benner.Corporativo.Definicoes.Materiais.PDProduto.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Produto.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Produto.Instance = value.Instance;
                    }
                    else
                    {
                        this.Produto.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Esp.ErpSuporte.Caisp.Business.Entidades.ICmProgramados ProgramadosInstance
        {
            get
            {
                if (Programados.Handle == null)
                {
					return null;
                }
                return Programados.Instance;
            }
            set
            {
                if (value == null)
                {
					Programados = null;
					return;
                }
                Programados.Instance = (Esp.ErpSuporte.Caisp.Business.Entidades.CmProgramados) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle ProgramadosHandle
        {
            get
            {
                return Programados.Handle;
            }
            set
            {
                Programados.Handle = value;
            }
        }
        
        /// <summary>
        /// Programação (PROGRAMADOS.)
        /// Opcional = N, Invisível = False, Pesquisar = K_CM_PROGRAMADOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Esp.ErpSuporte.Caisp.Business.Entidades.CmProgramados> Programados
        {
            get
            {
                return (Fields["PROGRAMADOS"] as EntityAssociation).Wrap<Esp.ErpSuporte.Caisp.Business.Entidades.CmProgramados>(Esp.ErpSuporte.Caisp.Business.Entidades.CmProgramados.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Programados.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Programados.Instance = value.Instance;
                    }
                    else
                    {
                        this.Programados.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Quantidade (QUANTIDADE.)
        /// Opcional = N, Invisível = False, Valor Mínimo = 99999999, Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<long> Quantidade
        {
            get
            {
                return Fields["QUANTIDADE"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["QUANTIDADE"] = value;
            }
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public CmProgramadoprodutosStatusListaItens Status
        {
            get
            {
                ListItem listItem = Fields["STATUS"] as ListItem;
				if (listItem != null)
					return new CmProgramadoprodutosStatusListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["STATUS"] = new ListItem(value.Index, value.Description);
				else
					Fields["STATUS"] = null;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioAlterouInstance
        {
            get
            {
                if (UsuarioAlterou.Handle == null)
                {
					return null;
                }
                return UsuarioAlterou.Instance;
            }
            set
            {
                if (value == null)
                {
					UsuarioAlterou = null;
					return;
                }
                UsuarioAlterou.Instance = (Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle UsuarioAlterouHandle
        {
            get
            {
                return UsuarioAlterou.Handle;
            }
            set
            {
                UsuarioAlterou.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuário alterou (USUARIOALTEROU.)
        /// Opcional = S, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios> UsuarioAlterou
        {
            get
            {
                return (Fields["USUARIOALTEROU"] as EntityAssociation).Wrap<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios>(Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.UsuarioAlterou.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.UsuarioAlterou.Instance = value.Instance;
                    }
                    else
                    {
                        this.UsuarioAlterou.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Metadata.Entities.IZGrupoUsuarios UsuarioincluiuInstance
        {
            get
            {
                if (Usuarioincluiu.Handle == null)
                {
					return null;
                }
                return Usuarioincluiu.Instance;
            }
            set
            {
                if (value == null)
                {
					Usuarioincluiu = null;
					return;
                }
                Usuarioincluiu.Instance = (Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Handle UsuarioincluiuHandle
        {
            get
            {
                return Usuarioincluiu.Handle;
            }
            set
            {
                Usuarioincluiu.Handle = value;
            }
        }
        
        /// <summary>
        /// Usuário incluiu (USUARIOINCLUIU.)
        /// Opcional = S, Invisível = False, Pesquisar = Z_GRUPOUSUARIOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios> Usuarioincluiu
        {
            get
            {
                return (Fields["USUARIOINCLUIU"] as EntityAssociation).Wrap<Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios>(Benner.Tecnologia.Metadata.Entities.ZGrupoUsuarios.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Usuarioincluiu.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Usuarioincluiu.Instance = value.Instance;
                    }
                    else
                    {
                        this.Usuarioincluiu.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
