//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.ErpSuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial interface IGnDocumentos : IEntityBase
    {
        
        /// <summary>
        /// Arquivo pdf (ARQUIVOPDF.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Common.FileField ArquivoPdf
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Data
        {
            get;
            set;
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Descricao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Link (LINK.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Link
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 16
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<long> Numero
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial interface IGnDocumentosDao : IBusinessEntityDao<IGnDocumentos>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial class GnDocumentosDao : BusinessEntityDao<GnDocumentos, IGnDocumentos>, IGnDocumentosDao
    {
        
        public static GnDocumentosDao CreateInstance()
        {
            return CreateInstance<GnDocumentosDao>();
        }
    }
    
    /// <summary>
    /// GnDocumentos
    /// </summary>
    [EntityDefinitionName("K_GN_DOCUMENTOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class GnDocumentos : BusinessEntity<GnDocumentos>, IGnDocumentos
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string ArquivoPdf = "ARQUIVOPDF";
			public const string Data = "DATA";
			public const string Descricao = "DESCRICAO";
			public const string Link = "LINK";
			public const string Nome = "NOME";
			public const string Numero = "NUMERO";
		}

        
        /// <summary>
        /// Arquivo pdf (ARQUIVOPDF.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.FileField ArquivoPdf
        {
            get
            {
                FileField fileField = Fields["ARQUIVOPDF"] as FileField;
				if (fileField == null)
					return null;

				if (fileField.Content == null)
				{
					System.IO.MemoryStream stream = new System.IO.MemoryStream();
					FileField.RetrieveContents(this, "ARQUIVOPDF", stream);
					fileField.Content = stream;
				}
				return fileField;
            }
            set
            {
                Fields["ARQUIVOPDF"] = value;

				FileField fileField = value as FileField;
				if (fileField != null)
					fileField.StoreContents(this, fileField.Content);
            }
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return Fields["DATA"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATA"] = value;
            }
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Descricao
        {
            get
            {
                return Fields["DESCRICAO"] as System.String;
            }
            set
            {
                Fields["DESCRICAO"] = value;
            }
        }
        
        /// <summary>
        /// Link (LINK.)
        /// Opcional = N, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Link
        {
            get
            {
                return Fields["LINK"] as System.String;
            }
            set
            {
                Fields["LINK"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 16
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<long> Numero
        {
            get
            {
                return Fields["NUMERO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NUMERO"] = value;
            }
        }
    }
}
