//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.ErpSuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial interface IGnDocumentos : IEntityBase
    {
        
        /// <summary>
        /// Arquivo pdf (ARQUIVOPDF.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Common.FileField ArquivoPdf
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<System.DateTime> Data
        {
            get;
            set;
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Descricao
        {
            get;
            set;
        }
        
        /// <summary>
        /// Editado (EDITADO.)
        /// Opcional = N, Invisível = True, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<bool> Editado
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 16
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<long> Numero
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        ICollection<Handle> PessoasAutorizadasHandles
        {
            get;
        }
        
        /// <summary>
        /// Privacidade Do Documento (PRIVACIDADE.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        GnDocumentosPrivacidadeDoDocumentoTabItens PrivacidadeDoDocumento
        {
            get;
            set;
        }
        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        GnDocumentosTipoListaItens Tipo
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial interface IGnDocumentosDao : IBusinessEntityDao<IGnDocumentos>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_GN_DOCUMENTOS
    /// </summary>
    public partial class GnDocumentosDao : BusinessEntityDao<GnDocumentos, IGnDocumentos>, IGnDocumentosDao
    {
        
        public static GnDocumentosDao CreateInstance()
        {
            return CreateInstance<GnDocumentosDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo PRIVACIDADE.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
    public class GnDocumentosPrivacidadeDoDocumentoTabItens : TabItems<GnDocumentosPrivacidadeDoDocumentoTabItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Publico.
        /// </summary>
        public static GnDocumentosPrivacidadeDoDocumentoTabItens ItemPublico;
        
        /// <summary>
        /// Valor = 2, Item = Privado.
        /// </summary>
        public static GnDocumentosPrivacidadeDoDocumentoTabItens ItemPrivado;
        
		public static implicit operator GnDocumentosPrivacidadeDoDocumentoTabItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(GnDocumentosPrivacidadeDoDocumentoTabItens item)
		{
			return item.Index;
		}
        
        static GnDocumentosPrivacidadeDoDocumentoTabItens()
        {
			ItemPublico = new GnDocumentosPrivacidadeDoDocumentoTabItens {Index = 1, Description ="Publico"};
			ItemPrivado = new GnDocumentosPrivacidadeDoDocumentoTabItens {Index = 2, Description ="Privado"};

			Items.Add(ItemPublico);
			Items.Add(ItemPrivado);

        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo TIPO.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
    public class GnDocumentosTipoListaItens : ListItems<GnDocumentosTipoListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Atas.
        /// </summary>
        public static GnDocumentosTipoListaItens ItemAtas;
        
        /// <summary>
        /// Valor = 2, Item = Estatutos.
        /// </summary>
        public static GnDocumentosTipoListaItens ItemEstatutos;
        
        /// <summary>
        /// Valor = 3, Item = Circulares Normativas.
        /// </summary>
        public static GnDocumentosTipoListaItens ItemCircularesNormativas;
        
        /// <summary>
        /// Valor = 4, Item = Desenvolvimento Agricola.
        /// </summary>
        public static GnDocumentosTipoListaItens ItemDesenvolvimentoAgricola;
        
		public static implicit operator GnDocumentosTipoListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(GnDocumentosTipoListaItens item)
		{
			return item.Index;
		}
        
        static GnDocumentosTipoListaItens()
        {
			ItemAtas = new GnDocumentosTipoListaItens {Index = 1, Description ="Atas"};
			ItemEstatutos = new GnDocumentosTipoListaItens {Index = 2, Description ="Estatutos"};
			ItemCircularesNormativas = new GnDocumentosTipoListaItens {Index = 3, Description ="Circulares Normativas"};
			ItemDesenvolvimentoAgricola = new GnDocumentosTipoListaItens {Index = 4, Description ="Desenvolvimento Agricola"};

			Items.Add(ItemAtas);
			Items.Add(ItemEstatutos);
			Items.Add(ItemCircularesNormativas);
			Items.Add(ItemDesenvolvimentoAgricola);

        }
    }
    
    /// <summary>
    /// GnDocumentos
    /// </summary>
    [EntityDefinitionName("K_GN_DOCUMENTOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class GnDocumentos : BusinessEntity<GnDocumentos>, IGnDocumentos
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string ArquivoPdf = "ARQUIVOPDF";
			public const string Data = "DATA";
			public const string Descricao = "DESCRICAO";
			public const string Editado = "EDITADO";
			public const string Nome = "NOME";
			public const string Numero = "NUMERO";
			public const string PessoasAutorizadas = "PESSOASAUTORIZADAS";
			public const string PrivacidadeDoDocumento = "PRIVACIDADE";
			public const string Tipo = "TIPO";
		}

        
        /// <summary>
        /// Arquivo pdf (ARQUIVOPDF.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.FileField ArquivoPdf
        {
            get
            {
                FileField fileField = Fields["ARQUIVOPDF"] as FileField;
				if (fileField == null)
					return null;

				if (fileField.Content == null)
				{
					System.IO.MemoryStream stream = new System.IO.MemoryStream();
					FileField.RetrieveContents(this, "ARQUIVOPDF", stream);
					fileField.Content = stream;
				}
				return fileField;
            }
            set
            {
                Fields["ARQUIVOPDF"] = value;

				FileField fileField = value as FileField;
				if (fileField != null)
					fileField.StoreContents(this, fileField.Content);
            }
        }
        
        /// <summary>
        /// Data (DATA.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Sem hora
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<System.DateTime> Data
        {
            get
            {
                return Fields["DATA"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATA"] = value;
            }
        }
        
        /// <summary>
        /// Descrição (DESCRICAO.)
        /// Opcional = S, Invisível = False, Tamanho = 30
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Descricao
        {
            get
            {
                return Fields["DESCRICAO"] as System.String;
            }
            set
            {
                Fields["DESCRICAO"] = value;
            }
        }
        
        /// <summary>
        /// Editado (EDITADO.)
        /// Opcional = N, Invisível = True, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<bool> Editado
        {
            get
            {
                return Fields["EDITADO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["EDITADO"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 16
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Numero (NUMERO.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<long> Numero
        {
            get
            {
                return Fields["NUMERO"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NUMERO"] = value;
            }
        }
        
        
        
        
        
        /// <summary>
        /// Privacidade Do Documento (PRIVACIDADE.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public GnDocumentosPrivacidadeDoDocumentoTabItens PrivacidadeDoDocumento
        {
            get
            {
                TabItem tabItem = Fields["PRIVACIDADE"] as TabItem;
				if (tabItem != null)
					return new GnDocumentosPrivacidadeDoDocumentoTabItens { Index = tabItem.Value, Description = tabItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["PRIVACIDADE"] = new TabItem(value.Index, value.Description);
				else
					Fields["PRIVACIDADE"] = null;
            }
        }
        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public GnDocumentosTipoListaItens Tipo
        {
            get
            {
                ListItem listItem = Fields["TIPO"] as ListItem;
				if (listItem != null)
					return new GnDocumentosTipoListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["TIPO"] = new ListItem(value.Index, value.Description);
				else
					Fields["TIPO"] = null;
            }
        }

        public ICollection<Handle> PessoasAutorizadasHandles => throw new NotImplementedException();
    }
}
