//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.ErpSuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_GN_CARDS
    /// </summary>
    public partial interface IKGnCards : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Consultasql (CONSULTASQL.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Consultasql
        {
            get;
            set;
        }
        
        /// <summary>
        /// Cor (COR.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Common.ColorField Cor
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Screnn (SCRENN.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Screnn
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor (VALOR.)
        /// Opcional = S, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Valor
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela K_GN_CARDS
    /// </summary>
    public partial interface IKGnCardsDao : IBusinessEntityDao<IKGnCards>
    {
    }
    
    /// <summary>
    /// DAO para a tabela K_GN_CARDS
    /// </summary>
    public partial class KGnCardsDao : BusinessEntityDao<KGnCards, IKGnCards>, IKGnCardsDao
    {
        
        public static KGnCardsDao CreateInstance()
        {
            return CreateInstance<KGnCardsDao>();
        }
    }
    
    /// <summary>
    /// KGnCards
    /// </summary>
    [EntityDefinitionName("K_GN_CARDS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class KGnCards : BusinessEntity<KGnCards>, IKGnCards
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Consultasql = "CONSULTASQL";
			public const string Cor = "COR";
			public const string Nome = "NOME";
			public const string Screnn = "SCRENN";
			public const string Valor = "VALOR";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// Consultasql (CONSULTASQL.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Consultasql
        {
            get
            {
                return Fields["CONSULTASQL"] as System.String;
            }
            set
            {
                Fields["CONSULTASQL"] = value;
            }
        }
        
        /// <summary>
        /// Cor (COR.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.ColorField Cor
        {
            get
            {
                return Fields["COR"] as Benner.Tecnologia.Common.ColorField;
            }
            set
            {
                Fields["COR"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Screnn (SCRENN.)
        /// Opcional = N, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Screnn
        {
            get
            {
                return Fields["SCRENN"] as System.String;
            }
            set
            {
                Fields["SCRENN"] = value;
            }
        }
        
        /// <summary>
        /// Valor (VALOR.)
        /// Opcional = S, Invisível = False, Tamanho = 10
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Valor
        {
            get
            {
                return Fields["VALOR"] as System.String;
            }
            set
            {
                Fields["VALOR"] = value;
            }
        }
    }
}
