//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using Esp.ErpSuporte.Caisp.Business.Entidades;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Esp.ErpSuporte.Caisp.Business.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela K_GN_CARDS
    /// </summary>
    public partial interface IKGnCards : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Consulta SQL (CONSULTASQL.)
        /// Opcional = N, Invisível = False, Tamanho = 500
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Consultasql
        {
            get;
            set;
        }
        
        /// <summary>
        /// Cor (COR.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        Benner.Tecnologia.Common.ColorField Cor
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Nome
        {
            get;
            set;
        }
        
        /// <summary>
        /// Ordem (ORDEM.)
        /// Opcional = N, Invisível = False, Tamanho = 4
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        string Ordem
        {
            get;
            set;
        }
        
        /// <summary>
        /// Envia para outra tela do APP (TELA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        KGnCardsTelaListaItens Tela
        {
            get;
            set;
        }
    }
    
    
    
    
    /// <summary>
    /// Esta classe contém os itens do campo TELA.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
    public class KGnCardsTelaListaItens : ListItems<KGnCardsTelaListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = SAC.
        /// </summary>
        public static KGnCardsTelaListaItens ItemSac;
        
        /// <summary>
        /// Valor = 2, Item = Eventos.
        /// </summary>
        public static KGnCardsTelaListaItens ItemEventos;
        
        /// <summary>
        /// Valor = 3, Item = Programacao.
        /// </summary>
        public static KGnCardsTelaListaItens ItemProgramacao;
        
        /// <summary>
        /// Valor = 4, Item = Financeiro.
        /// </summary>
        public static KGnCardsTelaListaItens ItemFinanceiro;
        
        /// <summary>
        /// Valor = 5, Item = Entregas.
        /// </summary>
        public static KGnCardsTelaListaItens ItemEntregas;
        
        /// <summary>
        /// Valor = 6, Item = Documentos.
        /// </summary>
        public static KGnCardsTelaListaItens ItemDocumentos;
        
        /// <summary>
        /// Valor = 7, Item = Contatos.
        /// </summary>
        public static KGnCardsTelaListaItens ItemContatos;
        
		public static implicit operator KGnCardsTelaListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(KGnCardsTelaListaItens item)
		{
			return item.Index;
		}
        
        static KGnCardsTelaListaItens()
        {
			ItemSac = new KGnCardsTelaListaItens {Index = 1, Description ="SAC"};
			ItemEventos = new KGnCardsTelaListaItens {Index = 2, Description ="Eventos"};
			ItemProgramacao = new KGnCardsTelaListaItens {Index = 3, Description ="Programacao"};
			ItemFinanceiro = new KGnCardsTelaListaItens {Index = 4, Description ="Financeiro"};
			ItemEntregas = new KGnCardsTelaListaItens {Index = 5, Description ="Entregas"};
			ItemDocumentos = new KGnCardsTelaListaItens {Index = 6, Description ="Documentos"};
			ItemContatos = new KGnCardsTelaListaItens {Index = 7, Description ="Contatos"};

			Items.Add(ItemSac);
			Items.Add(ItemEventos);
			Items.Add(ItemProgramacao);
			Items.Add(ItemFinanceiro);
			Items.Add(ItemEntregas);
			Items.Add(ItemDocumentos);
			Items.Add(ItemContatos);

        }
    }
    
    /// <summary>
    /// KGnCards
    /// </summary>
    [EntityDefinitionName("K_GN_CARDS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class KGnCards : BusinessEntity<KGnCards>, IKGnCards
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Consultasql = "CONSULTASQL";
			public const string Cor = "COR";
			public const string Nome = "NOME";
			public const string Ordem = "ORDEM";
			public const string Tela = "TELA";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// Consulta SQL (CONSULTASQL.)
        /// Opcional = N, Invisível = False, Tamanho = 500
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Consultasql
        {
            get
            {
                return Fields["CONSULTASQL"] as System.String;
            }
            set
            {
                Fields["CONSULTASQL"] = value;
            }
        }
        
        /// <summary>
        /// Cor (COR.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public Benner.Tecnologia.Common.ColorField Cor
        {
            get
            {
                return Fields["COR"] as Benner.Tecnologia.Common.ColorField;
            }
            set
            {
                Fields["COR"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        /// <summary>
        /// Ordem (ORDEM.)
        /// Opcional = N, Invisível = False, Tamanho = 4
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public string Ordem
        {
            get
            {
                return Fields["ORDEM"] as System.String;
            }
            set
            {
                Fields["ORDEM"] = value;
            }
        }
        
        /// <summary>
        /// Envia para outra tela do APP (TELA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "20.0.90.3")]
        public KGnCardsTelaListaItens Tela
        {
            get
            {
                ListItem listItem = Fields["TELA"] as ListItem;
				if (listItem != null)
					return new KGnCardsTelaListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["TELA"] = new ListItem(value.Index, value.Description);
				else
					Fields["TELA"] = null;
            }
        }
    }
}
